// examples/astro-basic/src/app/entry-server.tsx
import { hasHandler, handleFetch$ } from '@tanstack/bling/server'
import type { APIContext } from 'astro'
import * as ReactDOM from 'react-dom/server.browser'
import { App } from './root'
import { manifest } from './manifest'

export const requestHandler = async ({ request }: APIContext) => {
  // manifest['entry-client'] = 1
  if (hasHandler(new URL(request.url).pathname)) {
    return await handleFetch$({
      request,
    })
  }

  return new Response(await ReactDOM.renderToReadableStream(<App />), {
    headers: {
      'content-type': 'text/html',
    },
  })
}

// examples/astro-solid/src/app/entry-server.tsx
import { hasHandler, handleFetch$ } from '@tanstack/bling/server'
import type { APIContext } from 'astro'
import { renderToStringAsync } from 'solid-js/web'
import { App } from './root'
import { manifest } from 'astro:ssr-manifest'
import { manifestContext } from './manifest'

export const requestHandler = async ({ request }: APIContext) => {
  if (hasHandler(new URL(request.url).pathname)) {
    return await handleFetch$({
      request,
    })
  }

  return new Response(
    await renderToStringAsync(() => (
      <manifestContext.Provider value={manifest}>
        <App />
      </manifestContext.Provider>
    )),
    {
      headers: {
        'content-type': 'text/html',
      },
    },
  )
}
