// examples/astro-solid-hackernews/src/app/entry-server.tsx
import { hasHandler, handleFetch$ } from '@tanstack/bling/server'
import type { APIContext } from 'astro'
import { renderToStringAsync } from 'solid-js/web'
// @ts-ignore
import { manifest } from 'astro:ssr-manifest'
import { manifestContext } from './manifest'
import { routes } from './root'
import { Router, Routes, useRoutes } from '@solidjs/router'

export const requestHandler = async ({ request }: APIContext) => {
  if (hasHandler(new URL(request.url).pathname)) {
    return await handleFetch$({
      request,
    })
  }

  return new Response(
    await renderToStringAsync(() => {
      const Routes = useRoutes(routes)
      return (
        <manifestContext.Provider value={manifest}>
          <Router url={request.url.toString()}>
            <Routes />
          </Router>
        </manifestContext.Provider>
      )
    }),
    {
      headers: {
        'content-type': 'text/html',
      },
    },
  )
}

// examples/astro-react/src/app/entry-server.tsx
import { hasHandler, handleFetch$ } from '@tanstack/bling/server'
import type { APIContext } from 'astro'
// @ts-ignore
import * as ReactDOM from 'react-dom/server.browser'
import { App } from './root'
// @ts-ignore
import { manifest } from 'astro:ssr-manifest'
import { manifestContext } from './manifest'

export const requestHandler = async ({ request }: APIContext) => {
  if (hasHandler(new URL(request.url).pathname)) {
    return await handleFetch$({
      request,
    })
  }

  return new Response(
    await ReactDOM.renderToReadableStream(
      <manifestContext.Provider value={manifest}>
        <App />
      </manifestContext.Provider>,
    ),
    {
      headers: {
        'content-type': 'text/html',
      },
    },
  )
}
