// examples/astro-react-router/src/app/entry-server.tsx
import {
  hasHandler,
  handleFetch$,
  addDeserializer,
} from '@tanstack/bling/server'
import type { APIContext } from 'astro'
// @ts-ignore
import * as ReactDOM from 'react-dom/server.browser'
import { createStaticHandler } from '@remix-run/router'
import {
  createStaticRouter,
  StaticRouterProvider,
} from 'react-router-dom/server'
import { routes } from './root'
// @ts-ignore
import { manifest } from 'astro:ssr-manifest'
import { manifestContext } from './manifest'

addDeserializer({
  apply: (req) => req === '$request',
  deserialize: (value, ctx) => ctx.request,
})

export const requestHandler = async ({ request }: APIContext) => {
  // manifest['entry-client'] = 1
  if (hasHandler(new URL(request.url).pathname)) {
    return await handleFetch$({
      request,
    })
  }

  let { query } = createStaticHandler(routes)
  let context = await query(request)

  if (context instanceof Response) {
    throw context
  }

  let router = createStaticRouter(routes, context)

  return new Response(
    await ReactDOM.renderToReadableStream(
      <manifestContext.Provider value={manifest}>
        <StaticRouterProvider
          router={router}
          context={context}
          nonce="the-nonce"
        />
      </manifestContext.Provider>,
    ),
    {
      headers: {
        'content-type': 'text/html',
      },
    },
  )
}

// examples/astro-solid-hackernews/src/app/entry-server.tsx
import { hasHandler, handleFetch$ } from '@tanstack/bling/server'
import type { APIContext } from 'astro'
import { renderToStringAsync } from 'solid-js/web'
// @ts-ignore
import { manifest } from 'astro:ssr-manifest'
import { manifestContext } from './manifest'
import { routes } from './root'
import { Router, Routes, useRoutes } from '@solidjs/router'

export const requestHandler = async ({ request }: APIContext) => {
  if (hasHandler(new URL(request.url).pathname)) {
    return await handleFetch$({
      request,
    })
  }

  return new Response(
    await renderToStringAsync(() => {
      const Routes = useRoutes(routes)
      return (
        <manifestContext.Provider value={manifest}>
          <Router url={request.url.toString()}>
            <Routes />
          </Router>
        </manifestContext.Provider>
      )
    }),
    {
      headers: {
        'content-type': 'text/html',
      },
    },
  )
}
